122 - WIP: Implement SearchManagerContext and useSearchManager (Draft)
AlexsLemonade/refinebio-web pull request #126
Opened 2023-06-06 21:30 UTC by nozomione

## Issue Number

#122 

## Purpose/Implementation Notes

Using the context API, implemented a search manager context SearchManagerContext and its hook useSearchManager which includes necessary methods to perform searches.

## Types of changes
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Functional tests

List out the functional tests you've completed to verify your changes work locally.

## Checklist

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in

2023-06-30 03:56 UTC, nozomione commented
@davidsmejia as requested today's 1:1, I prepared the PRs for you to review tomorrow during the time you allocated time for PR review.

**3** of 3

This is the last PR for review. This is the latest search result page. I also updated my initial [PR comment](https://github.com/AlexsLemonade/refinebio-web/pull/126#issue-1744640266) and included a lit of files for you to review. Let me know if you have any questions!

**NOTE:** 
- After this PR review,  PR [123](https://github.com/AlexsLemonade/refinebio-web/pull/128), and then [131](https://github.com/AlexsLemonade/refinebio-web/pull/131) should be reviewed. 
- Due to the dataset manager implementation and API integration (currently in progress), some of the older PRs (for the dataset/download pages) will be be outdated and closed.

2023-07-20 19:48 UTC, davidsmejia requested changes
Please keep parity with the API and the client for parameters. 
- p should not exist on the client side in the new version, we should only have offset and limit

I also do not understand what's going on in `src/helpers/getSearchQueryForAPI.js`. If this is to support previous existing urls we should make that clearer in the code.

Other than that looks good!

2023-07-20 20:49 UTC, nozomione commented
>  p should not exist on the client side in the new version, we should only have offset and limit

I used `p`(the currently selected page number) and `size` (the number of results that are currently showing on the page) parameters not only to match the refinebio-frontend implementation, but also to create a user-friendly URL. For instance, the interpretation of `p` would be easier for users to understand than `offset` since it's commonly used (e.g., when a user want to go to page 5 by simply altering the URL). What do you think 💬 ? 
 
> I also do not understand what's going on in `src/helpers/getSearchQueryForAPI.js`. If this is to support previous existing urls we should make that clearer in the code.

This helper is used to filter out any parameters(e.g., `empty`, `sortby`) that are only used on the client side when making the API requests to the server. In the helper file, I'll include a comment describing what it does and improve it as needed 👍  

> Other than that looks good!

 🥳 🎉

2023-08-01 19:12 UTC, davidsmejia approved these changes

2023-08-01 19:12 UTC, merged