24 - Support alphanumeric characters on badged buttons before deploying production
AlexsLemonade/refinebio-web pull request #156
Opened 2023-08-16 20:03 UTC by nozomione

## Issue Number

Closing #24

- The base PR was [#153](https://github.com/AlexsLemonade/refinebio-web/pull/153) (which will be merged into `dev` first) 
- The commit of this PR starts at 

The files changed in this PR:

<ins>New files added (2)</ins>
- helpers/abbreviateNumber.js
- components/shared/BadgedButton.js

<ins>Files updated (3)</ins> 

(*includes minor changes)

- helpers/formatNumbers.js

- components/
   - Header/GlobalNav.js
   - shared/NumberBadge.js

## Purpose/Implementation Notes
Based on the requirement, created the shared component `BadgedButton` which supports abbreviated numbers. 

@dvenprasad please review the latest UI [here]().  

## Types of changes

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Functional tests

List out the functional tests you've completed to verify your changes work locally.

## Checklist
- [x] Lint and unit tests pass locally with my changes

2023-08-17 17:21 UTC, davidsmejia approved these changes

2023-08-21 19:18 UTC, dvenprasad requested changes
It looks good but the text seems a bit small. 
Could we make the following tweaks?
- Increase the font size to 13px
- Reduce the badge padding to 2px,8px

2023-08-21 19:44 UTC, nozomione commented
>     * Increase the font size to 13px
>     * Reduce the badge padding to 2px,8px

@dvenprasad  The UI was updated and now ready for another look 🎨 [here](https://refinebio-ff8og6clv-ccdl.vercel.app/)!

2023-08-22 14:21 UTC, dvenprasad approved these changes
LGTM! 
🦓 🦓 🦓

2023-08-22 14:27 UTC, merged