179 - Implement useDatasetAction hook for dataset actions
AlexsLemonade/refinebio-web pull request #183
Opened 2023-09-14 21:33 UTC by nozomione

## Issue Number

Closing #179

## Purpose/Implementation Notes
Based on the implementation details, implemented `useDatasetAction` hook.

## Types of changes
- New feature (non-breaking change which adds functionality)

## Checklist
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-26 21:17 UTC, davidsmejia requested changes
Looking good, please give the variable names in the hook some more meaning and this is good to go!

2023-09-26 21:17 UTC, davidsmejia commented on src/hooks/useDatasetAction.js
This looks good!

I would like you to make the following changes to improve readability and make the usage more consistent.

For help understanding which dataset is which, please update the variable / parameter names to:
- `data1` -> `defaultUserDataset`
- `data2` -> `defaultOtherDataset`
- `d1` -> `userDataset`
- `d2` -> `otherDataset`
- derivative variable names should also be updated

2023-09-26 21:21 UTC, davidsmejia commented on src/hooks/useDatasetAction.js
> +  const totalSamplesInDataset = () => {
```suggestion
  const getTotalSamplesInDataset = () => {
```

Without the get I would assume this is a static value, to make it more obvious that it is a getter please prefix with `get`

2023-09-26 21:23 UTC, davidsmejia requested changes
While stepping through anther PR I noticed that we should adhere to keeping getters prefixed with `get` so it is clearer that the extracted attribute is a function and not an already computed value.

2023-09-26 21:23 UTC, davidsmejia commented on src/hooks/useDatasetAction.js
> +  const allProcessedInDataset = () => {
```suggestion
  const getAllProcessedInDataset = () => {
```

2023-09-26 21:23 UTC, davidsmejia commented on src/hooks/useDatasetAction.js
> +  const anyProcessedInDataset = () =>
```suggestion
  const getAnyProcessedInDataset = () =>
```

2023-09-26 21:23 UTC, davidsmejia commented on src/hooks/useDatasetAction.js
> +  const intersectDatasets = () => {
```suggestion
  const getDatasetIntersection = () => {
```

2023-09-26 21:30 UTC, davidsmejia commented
While looking at this. I think that another option besides renaming the functions for clarity would be decide if the value can be derived during execution of the hook, we can just export it as a value and it does not need to be a function. Either that or renaming are acceptable to me.

2023-10-04 19:43 UTC, nozomione commented on src/hooks/useDatasetAction.js
This hook takes the `data` object in user-created dataset and downloadable samples from the API response (all processed samples in each experiment) which are selected by a user via the search page (no dataset id associated with it but those samples in an experiment were added using the experiment accession code and `all` prop). 

In refinebio-frontend, I see that the term <code>data<strong>Slice</strong></code> is commonly used to distinguish between a `dataset` and a `data` objects in a dataset.

Could we possibly use the `userDataSlice` and `apiDataSlice` (or `dataSliceInExperiment`) or something similar?

2023-10-04 19:48 UTC, nozomione commented
@davidsmejia based on your suggestions, I've updated the method names. Please take a look at the comment on parameter names and let me know your thought on this, thank you David.

2023-10-04 21:24 UTC, davidsmejia reviewed
Name changes are much more descriptive, thanks!

2023-10-04 21:24 UTC, davidsmejia commented on src/hooks/useDatasetAction.js
Ah good point, I think instead of `dataslice`, we use `datasetData` as a convention since it is clearer.

Based on your suggestions and my concern I think that `datasetData` and `datasetDataChanges` more clearly illustrate the contents of those variables and also describes how these functions work.

`datasetDataChanges` adequately informs me of the type of data that is expected. That it should look like a datasets `data` attribute and that it is intended to be a potential change to `data` passed as the first parameter.

I can easily see this hook being used anywhere we want to diff changes so lets keep the names distinct from their specific interactions causing their invocation.

2023-10-04 22:20 UTC, nozomione commented
@davidsmejia based on your feedback, I've renamed he parameters for this hook 9144adc542fdcfc7855ea0ace445a5d5c5b56421, please take a look.  

The `hasSameSamples (d1, d2)` is an internal helper method that compares any two `data` objects, so I left the parameter names as they were (If you have any preferences, please let me know).

2023-10-06 19:11 UTC, davidsmejia reviewed
Please update these names to `datasetDataOne` and `datasetDataTwo` in that function and then this looks good to me.

2023-10-06 19:18 UTC, davidsmejia approved these changes
LGTM

2023-10-06 19:22 UTC, merged