180 - Implement dataset action button component using useDatasetAction
AlexsLemonade/refinebio-web pull request #185
Opened 2023-09-15 19:12 UTC by nozomione

## Issue Number

Closing #180

## Purpose/Implementation Notes
Based on the requirement, implemented the dataset action button component using `useDatasetAction` hook.
## Types of changes
- New feature (non-breaking change which adds functionality)

## Checklist
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-29 20:56 UTC, davidsmejia requested changes
Looking good, just some minor changes requested.

2023-09-29 20:56 UTC, davidsmejia commented on src/components/shared/DatasetActionButton/index.js
> +/* eslint-disable react/jsx-props-no-spreading */
Could you move this to the individual lines where it applies.

2023-09-29 20:56 UTC, davidsmejia commented on src/components/shared/DatasetActionButton/AddToDatasetButton.js
> +  btnType = 'primary',
let's just pass `primary` and `secondary` as props here

2023-09-29 20:56 UTC, davidsmejia commented on src/components/shared/DatasetActionButton/index.js
> +  btnType,
again lets just pass `primary` and `secondary` here

2023-09-29 20:56 UTC, davidsmejia commented on src/components/shared/DatasetActionButton/AddRemainingButton.js
I think for consistency, `AddRemainingDatasetButton` is more appropriate. Another option would be to rename the other components and remove `Dataset` from their names.

2023-10-05 16:05 UTC, nozomione commented
@davidsmejia based on your feedback, I've updated the codebase. Please take a look.

2023-10-06 19:13 UTC, davidsmejia approved these changes
LGTM

2023-10-06 19:33 UTC, merged