166 - Implement useOneOffExperiment hook for one-off experiment dataset downloads
AlexsLemonade/refinebio-web pull request #215
Opened 2023-10-13 20:09 UTC by nozomione

## Issue Number

Closing #166

## Purpose/Implementation Notes
Implement edthe hook `useOneOffExperiment` which includes the states and methods required to handle the file download for one-off experiment dataset. 

## Types of changes
- New feature (non-breaking change which adds functionality)

## Checklist
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-30 18:50 UTC, davidsmejia requested changes
One change requested otherwise looking good

2023-10-30 18:50 UTC, davidsmejia commented on src/hooks/useOneOffExperiment.js
> +    const [experiment] = processingExperiments.filter(
Can we use Array.prototype.find here?

2023-10-30 22:35 UTC, nozomione commented
@davidsmejia , please review PR https://github.com/AlexsLemonade/refinebio-web/pull/218 first before reviewing this PR. 

🗒️  I've added a note about this to the **Issue Number** section and also left a comment (https://github.com/AlexsLemonade/refinebio-web/pull/205#issuecomment-1770991338) in previous PR https://github.com/AlexsLemonade/refinebio-web/pull/205 (which was already reviewed & approved), thank you.

2023-11-01 18:24 UTC, davidsmejia approved these changes
I think tracking both `startTimer` and `timerId` is redundant but we can address that at another time. Otherwise this looks good.

2023-11-01 18:55 UTC, merged