30 - Implement About Page
AlexsLemonade/refinebio-web pull request #33
Opened 2022-11-15 00:49 UTC by nozomione

## Issue Number
#30 

Figma Mockup: [About](https://www.figma.com/file/2cxEjUKA4ACTjDYSnDEWpR/refinebio-master?node-id=187%3A6298&t=rLN6bTbL0ji4Rs2d-0)

(This PR is a dependent of the PR [#29](https://github.com/AlexsLemonade/refinebio-web/pull/32) and was created based on the branch `nozomione/29-implement-landing-page`)

## Purpose/Implementation Notes
> Add the necessary components and implement them on the about page.

Implemented the about page using the global components.

<details>
<summary>Files related to this PR</summary>

---
</details>

- [ ] UI review w/ @dvenprasad - please review the UI [here](https://refinebio-web-git-nozomione-29-implement-landing-page-ccdl.vercel.app/), thank you!

(After passing the UI review, @davidsmejia will be added to the reviewers.)

## Types of changes

What types of changes does your code introduce?

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] Lint and unit tests pass locally with my changes

2022-11-16 15:30 UTC, dvenprasad requested changes
All of the components, font sizes looks good! I have layout comment

There's two margins, the outer one which is the bounds of the navigation bar and an inner one which is for the content: 
![Screen Shot 2022-11-16 at 10 26 28 AM](https://user-images.githubusercontent.com/15315514/202222643-b13651d9-be86-4d0b-906a-9712242d7de9.png)

Here, there seems to be only one which is the width of the navigation bar, but the content should be contatined within the bounds of the second one like above:
![Screen Shot 2022-11-16 at 10 27 00 AM](https://user-images.githubusercontent.com/15315514/202223015-1c33b8a4-8fda-4991-b9d5-e19e012ce0ec.png)

2022-11-16 16:32 UTC, nozomione commented
> All of the components, font sizes looks good! I have layout comment
> 
> There's two margins, the outer one which is the bounds of the navigation bar and an inner one which is for the content: ![Screen Shot 2022-11-16 at 10 26 28 AM](https://user-images.githubusercontent.com/15315514/202222643-b13651d9-be86-4d0b-906a-9712242d7de9.png)
> 

In this case, the page content will be shifted more to the right side. Or do you prefer it to be centered of the page? Please let me know!

2022-11-16 19:36 UTC, dvenprasad commented
Let's center the content

2022-11-16 20:49 UTC, nozomione commented
> Let's center the content

@dvenprasad, the UI is ready for your review, thank you!

2022-11-16 20:53 UTC, dvenprasad approved these changes
Looking good! 🦔 🦔 🦔

2023-04-06 13:07 UTC, nozomione commented on src/components/About/AboutHero.js
> +  // TEMP
The current refinebio pull those data from the [apiData.json](https://github.com/AlexsLemonade/refinebio-frontend/blob/dev/src/apiData.json) file (a cache stored in the `src` directory). Once the file is added(if we'll be using it), those temp object will be removed 🗑

2023-04-06 13:12 UTC, nozomione commented on src/themes/colors.js
> +  gradient_light: 'linear-gradient(360deg, #DFE9F3 7.13%, #FFFFFF 75%)',
Please see the PR [107- Update All Themeing Variable Names To Camel Case](https://github.com/AlexsLemonade/refinebio-web/pull/110). Btw, thank you for coming up with this idea 💡 to reduce the merge conflict!

2023-05-02 23:36 UTC, merged